services:

  linux-1:
    build: .
    container_name: linux-1
    hostname: linux-1
    restart: unless-stopped
    ports:
      - "2221:22"
    volumes:
      - ./shared:/shared
    networks:
      - testnet

  linux-2:
    build: .
    container_name: linux-2
    hostname: linux-2
    restart: unless-stopped
    ports:
      - "2222:22"
    volumes:
      - ./shared:/shared
    networks:
      - testnet

  linux-3:
    build: .
    container_name: linux-3
    hostname: linux-3
    restart: unless-stopped
    ports:
      - "2223:22"
    volumes:
      - ./shared:/shared
    networks:
      - testnet

  linux-4:
    build: .
    container_name: linux-4
    hostname: linux-4
    restart: unless-stopped
    ports:
      - "2224:22"
    volumes:
      - ./shared:/shared
    networks:
      - testnet

  linux-5:
    build: .
    container_name: linux-5
    hostname: linux-5
    restart: unless-stopped
    ports:
      - "2225:22"
    volumes:
      - ./shared:/shared
    networks:
      - testnet

networks:
  testnet:
    driver: bridge
