spring.application.name=DynamicCode

server.port=8888

# 1. ?cie?ka do pliku bazy na dysku
spring.datasource.url=jdbc:h2:file:./data/moja_baza;DB_CLOSE_ON_EXIT=FALSE

# 2. Dane logowania (standardowe dla H2)
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# 3. Ka?esz Hibernate automatycznie tworzy? tabele na podstawie Twoich klas w Javie
spring.jpa.hibernate.ddl-auto=update