spring.application.name=DynamicCode
server.port=8888

# 1. ?cie?ka do pliku bazy na dysku
spring.datasource.url=jdbc:h2:file:./data/moja_baza;DB_CLOSE_ON_EXIT=FALSE;max_compact_time=10000
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# 2. Automatyczne tworzenie tabel
spring.jpa.hibernate.ddl-auto=update

# ===================================================================
# NOWE: Konfiguracja dla przesy?ania du?ych plików (np. 75MB+)
# ===================================================================

# Maksymalny rozmiar pojedynczego przesy?anego pliku
spring.servlet.multipart.max-file-size=150MB

# Maksymalny rozmiar ca?ego ??dania HTTP (plik + parametry)
spring.servlet.multipart.max-request-size=150MB

# Zwi?kszenie limitu wielko?ci danych formularza dla wbudowanego Tomcata
server.tomcat.max-http-form-post-size=150MB