name: Deploy Mintlify to Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Mintlify
        run: npm install -g mintlify

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Build Mintlify Docs
        # Dodaliśmy 'working-directory', żeby skrypt odpalił się tam, gdzie masz docs.json i pliki mdx
        working-directory: ./docs
        run: |
          mintlify export --out-dir ../out
          touch ../out/.nojekyll

      - name: Inject Base Path to HTML
        run: |
          find ./out -name "*.html" -exec sed -i 's|"/_next|"/App-Instance-Manager/_next|g' {} +
          find ./out -name "*.html" -exec sed -i 's|"_next|"App-Instance-Manager/_next|g' {} +
          find ./out -name "*.html" -exec sed -i 's|href="/|href="/App-Instance-Manager/|g' {} +
          find ./out -name "*.html" -exec sed -i 's|href="https://bartoszkac.github.io/|href="https://bartoszkac.github.io/App-Instance-Manager/|g' {} +

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './out'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4